# Generated by Django 5.1.5 on 2025-03-12 11:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ips',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), blank=True, null=True, size=None),
        ),
    ]
