# Generated by Django 5.1.5 on 2025-02-19 06:02

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=200, validators=[core.validators.validate_email], verbose_name='Email'),
        ),
    ]
