# Generated by Django 5.1.5 on 2025-04-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='name',
        ),
    ]
