# Generated by Django 5.1.5 on 2025-02-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='image/index/menu/'),
        ),
    ]
