# Generated by Django 5.1.5 on 2025-02-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='weight'),
        ),
    ]
